name: Menu Service Dev CI/CD
on:
  push:
    branches:
      - "main"
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server 성공 !
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
          # 프로젝트 디렉토리로 이동
            cd /home/ubuntu/Gmenu
            
            # main 브랜치의 최신 변경사항 가져오기
            git pull origin main
            
            # 기존 application.yml 파일 삭제
            rm -rf /home/ubuntu/Gmenu/src/main/resources/application.yml
            
            # resources 디렉토리 생성 (없는 경우를 대비)
            mkdir -p /home/ubuntu/Gmenu/src/main/resources
            
            # 새로운 application.yml 파일 생성
            touch /home/ubuntu/Gmenu/src/main/resources/application.yml
            
            # GitHub Secrets에 저장된 YML 내용을 application.yml에 작성
            echo "${{ secrets.YML }}" > /home/ubuntu/Gmenu/src/main/resources/application.yml
            
            # application.yml 파일 권한 확인
            ls -l /home/ubuntu/Gmenu/src/main/resources/application.yml
            
            # 8080 포트에서 실행 중인 프로세스 종료 (에러 무시)
            sudo fuser -k -n tcp 8080 || true
            
            # gradlew 실행 권한 부여
            chmod +x ./gradlew
            
            # 프로젝트 새로 빌드
            ./gradlew clean build
            
            # 빌드된 jar 파일이 있는 디렉토리로 이동
            cd build/libs
            
            # jar 파일 백그라운드 실행 (로그는 output.log에 저장)
            nohup java -jar *.SNAPSHOT.jar > ./output.log 2>&1 &