## 하나의 workflow 단위
#
## workflow 이름
#name: Github Actions 실행시켜보기
#
## 어떤 시점에, 어떤 경우에 해당 workflow를 실행시키고 싶은지
## main에 push가 됐을 때 workflow를 실행시키고 싶다.
#on:
#  push:
#       branches:
#         - main
#
## 하나의 workflow는 한 개 이상의 job으로 구성된다.
## 여러 job은 기본적으로 병렬적으로 수행한다.
#jobs:
#
#  # 하나의 Job에 대한 식별자
#  My-Deploy-job:
#
#    # 최신의 우분투 버전에서 실행시킨다.
#    runs-on:  ubuntu-latest
#
#    #Job은 여러 step들로 구성되어 있다.
#    steps:
#      # job의 이름
#      - name : Hello World 찍기
#        run: echo "Hello"

name: GAJI Service Dev CI/CD
on:
  push:
    branches:
      - "main"
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server 성공 !
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/instargram-server
            git pull origin main
            rm -rf src/main/resources/application.yml
            mkdir -p src/main/resources
            touch src/main/resources/application.yml
            echo "${{ secrets.YML }}" > src/main/resources/application.yml
            ls -l src/main/resources/application.yml
            sudo fuser -k -n tcp 8080 || true
            chmod +x ./gradlew
            ./gradlew clean build
            cd build/libs
            nohup java -jar *.SNAPSHOT.jar > ./output.log 2>&1 &